### PR TITLE
Parallelize glyph loading

### PR DESCRIPTION
**Pull request by Riey**
Speed up `load` bench 5 times fast(on my 5800X machine) even faster than other libraries

### CODE REVIEW

**Comment by mooman219** [comment]
Sorry for the delay on running the github actions, I was traveling. I think this is a good idea, but my immediate concern is code duplication. Mind refactoring this to share more logic in the two codepaths?

**Comment by Riey** [comment]
> 
> 
> Sorry for the delay on running the github actions, I was traveling. I think this is a good idea, but my immediate concern is code duplication. Mind refactoring this to share more logic in the two codepaths?

I merge duplicated code with closure

Benchmark result looks the same, but if you care, I can change it to macro.

**Comment by mooman219** [comment]
So in retrospect, I regret having the flag `disable_simd` instead of adding a new flag called `simd` and having it be default, that way I can have a github workflow for `--all-features`.

In the meantime, mind adding two entries to add the `parallel` feature below the two locations listed below?
https://github.com/mooman219/fontdue/blob/2bfda9dc70c292379eeb785d9d6596f7fe82a929/.github/workflows/format.yml#L17-L19

https://github.com/mooman219/fontdue/blob/2bfda9dc70c292379eeb785d9d6596f7fe82a929/.github/workflows/build.yml#L18-L20

I'll take a pass later to refactor the feature names so we don't have to do this for every new feature flag in the future.

**Comment by Riey** [comment]
I'm sorry, but recently I don't have time to fix this please feel free to edit this branch for merge or close PR

**Comment by mooman219** [comment]
Yeah that's reasonable, I'll merge and clean it up

**Pull request merged**
