### PR TITLE
Optimized SIMD bitmap generation

### PR DESCRIPTION
**Pull request by PENGUINLIONG**
All intrinsics are SSE2 and below.

### CODE REVIEW

**Comment by mooman219** [comment]
This doesn't produce a measurable improvement in the benchmark.

**Comment by PENGUINLIONG** [comment]
The improvement starts to be visible after 80px. I ran the benchmarks on Intel i7-9700 and here are the logs: [fontdue-bench.log](https://gist.github.com/PENGUINLIONG/bc42ae40d724e6083f2bab94b09e1d3b/revisions?diff=split)

On the left side it's the log generated by the latest master(aea96ed), and on the right by this PR (873c12b).

**Comment by mooman219** [comment]
Fontdue's benchmark is vulnerable to CPU noise (moreso on many core systems), and can see up to a 30% increase in time depending on how it gets scheduled. It's recommended to run each benchmark 2-3 times and take the best between them for each bench to establish some stability. Could you do that on your i7 9700 and post the results?

The best of 4 runs with this change at 200px nets me 222.81us. Without this change it's 220.16us. CPU is an AMD 3950x.

I'm skeptical that Intel may have a bad implemented for _mm_set1_ps if your diffs are confirmed.

**Comment by PENGUINLIONG** [comment]
Interesting. I'm gonna try it on my single threaded server and see if it actually works.

**Comment by PENGUINLIONG** [comment]
Okay, I checked the emitted assembly. I intended to improve the XMM register read at the end of the loop, while I found that rustc with `-O` enabled is handling this automatically. The machine codes are exactly the same between the versions. :)
Closing this PR.

**Comment by mooman219** [comment]
That's good to hear the compiler is smart enough to do that. Thank you though for looking into this!

**Pull request closed without merging**
