### PR TITLE
keep the scale api uniformity

### PR DESCRIPTION
**Pull request by TakWolf**

### CODE REVIEW

**Comment by TakWolf** [comment]
By the way,  what is the planning time to publish the version 0.0.5 and 0.1.0?

**Comment by mooman219** [comment]
I can do 0.0.5 today to get the line metrics change out. I was going to finish kerning first but that's not really important without layout. I can push that to 0.0.6. I was going to skip to 1.0.0 directly after layout is done because the versions don't really matter anyway

**Comment by mooman219** [comment]
As for the change, why do you need to rescale a metric? Rescaling a metric multiple times can cause inaccuracies since it's truncating at the width and height (which is why I didn't add scale to metrics originally, easy to misuse)

**Comment by TakWolf** [comment]
> As for the change, why do you need to rescale a metric? Rescaling a metric multiple times can cause inaccuracies since it's truncating at the width and height (which is why I didn't add scale to metrics originally, easy to misuse)

For my situation, the window has a `scale_factor`. For example, on the macOS Retina Display, the `scale_factor` is 2.0, it's means that the window with logical size 100 * 100, in fact has physical size 200 * 200. (This is the winit implement way.)

So to render the text on retina display, need to fit the `scale_factor` to keep text clearly. (Otherwise the text will scale and vague.)

```rust
let scale_factor = window.scale_factor();
let logical_text_size = 20.0;
let physical_text_size = logical_size * scale_factor;
let physical_line_metrics = font.horizontal_line_metrics(physical_text_size);
let logical_line_metrics = physical_line_metrics.scale(1.0 / scale_factor);
let (physical_metrics, bitmap) = font.rasterize(character, physical_text_size);
let logical_metrics = physical_metrics.scale(1.0 / scale_factor); // <-- need a fn scale

let uv = cache.push(physical_metrics, bitmap);
let vertices = layout.calculate(logical_line_metrics, logical_metrics);
```

All the meta struct has the scale fn, but `Metrics` not. It's not necessary, but it is convenient.

===================

I have noticed the metrics.width and metrics.height is usize, and use `ceil()`.
So I am not sure if this is a best way to do that.

**Comment by TakWolf** [comment]
> I can do 0.0.5 today to get the line metrics change out. I was going to finish kerning first but that's not really important without layout. I can push that to 0.0.6. I was going to skip to 1.0.0 directly after layout is done because the versions don't really matter anyway

I am not urgent need v0.0.5, I am just checking. There is no need to publish today.

=================================

I hope `fontdue` keep simple.(Only has parser, meta data and rasterize)
And usage a extra crate to implement the layout system. (`fontdue-layout`)

Because layout system is so complex may cause code bloat and may not general.
(Reading order、Coordinate System and other problem)

**Comment by mooman219** [comment]
> I have noticed the metrics.width and metrics.height is usize, and use ceil().
So I am not sure if this is the best way to do that.

Height and width in the raster are rounded up with `ceil`. This is because if the height/width of the glyph is say 14.1, the raster will need to 15 pixels of height/width to raster the glyph.

**Pull request closed without merging**
