### PR TITLE
Relicense to `MIT OR Apache-2.0 OR Zlib`

### PR DESCRIPTION
**Pull request by lunabunn**
As per the discussion in #112, I am initiating the process to relicense this project to the `MIT OR Apache-2.0 OR Zlib` triple license.

## Rationale for Licensing

Currently `fontdue` is licensed solely under `MIT`. In addition to not being as compatible as it could be with the rest of the ecosystem, most of which uses the `MIT OR Apache-2.0` dual license, `MIT` is also problematic in that in lacks a patent protection clause and an explicit contribution clause. In fact, [Rust itself is only keeping around `MIT` as a licensing option (instead of using just `Apache-2.0`) for GPLv2 compat](https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952/4).

If this project were to be dual-licensed under `Apache-2.0` and `MIT`, contributors would be providing the `Apache-2.0` patent grant, even though the project will still remain usable with the `MIT` license. It will also be more compatible with the rest of the ecosystem. Adding a third `Zlib` licensing option then grants the additional flexibility of not needing to include attribution or license information in product distributions that do not include source code.

This permissive, flexible, and compatible licensing would be ideal for a crate such as `fontdue` that is most likely to be used indirectly as dependencies of other crates in its users' dependency graphs.

## Contributor checkoff

Being a change in license, this requires all contributors who have made copyrightable changes to the `fontdue` repository to agree.

For simplicity (and because IANAL), given below is a list of *all* contributors to the fontdue project. If you agree to relicensing, please comment verbatim:

> I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to choose any one at their option.

If you have any concerns, please leave those in this issue thread as well so that they can be discussed.

- [x] @mooman219 
- [x] @robmcl4 
- [x] @weswigham 
- [x] @twitchyliquid64 
- [x] @Brooooooklyn 
- [x] @ryan-scott-dev 
- [x] @cedric-h 
- [x] @MarimeGui 
- [x] @maroider 
- [x] @Some-Dood 
- [x] @bschwind 
- [x] @tronical 
- [x] @Riey 
- [x] @deeprobin 
- [x] @deprilula28 
- [x] @avl 
- [x] @avafloww

### CODE REVIEW

**Comment by maroider** [comment]
I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to chose any one at their option.

**Comment by bschwind** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by weswigham** [comment]
I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to chose any one at their option.

**Comment by deeprobin** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by Some-Dood** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

Thanks for the heads up, by the way!

**Comment by tronical** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by avafloww** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by twitchyliquid64** [comment]
I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to chose any one at their option.

:partying_face:

**Comment by robmcl4** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by ryan-scott-dev** [comment]
I license past and future contributions under the triple `MIT OR Apache-2.0 OR Zlib` license, allowing licensees to chose any one at their option.

**Comment by MarimeGui** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by Brooooooklyn** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by cedric-h** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to chose any one at their option.

**Comment by avl** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by avl** [comment]
(I'm sorry for being so late to answer. I think I was notified when I was pinged when this PR was opened, but I didn't read enough to realize I was being asked to take action. Sorry about that! Good initiative!)

**Comment by deprilula28** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by grovesNL** [comment]
I license past and future contributions under the triple MIT OR Apache-2.0 OR Zlib license, allowing licensees to choose any one at their option.

**Comment by mooman219** [comment]
Thanks everyone!

**Pull request merged**
